id: IE37540B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:09:16+00:00'
last_modified: '2022-06-09T04:58:20.268572+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14530
  title: རྩོམ་ཡིག་ལ་འཇུག་པའི་སྒོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9692':
      image_group_id: I1KG16268
      title: ''
      total_pages: 230
      order: 1
      base_file: 9692.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
