id: P008168
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14530
  title: རྩོམ་ཡིག་ལ་འཇུག་པའི་སྒོ།
  author: ''
  volumes:
    518d32118ee642b2a8711bcc2ca31362:
      image_group_id: I1KG16268
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
